(in-package #:binding)

(defun input-functions-demo ()
  (let ((msg "Just a string")
        (row 0)
        (col 0)
        (str (foreign-alloc :string :count 80) ))
    (initscr)
    (clear)
    (refresh)
    (setf row (getmaxy *stdscr*))
    (setf col (getmaxx *stdscr*))
    (mvprintw (floor (/ row 2))
              (floor (/ (- col (length msg)) 2))
              "%s" :string msg)
    (getstr str)
    (mvprintw (- *lines* 2) 0 "You entered: %s" :String str )
    (refresh)
    (getch)
    (endwin)))
