(in-package #:binding)

(include "ncurses.h")

;; MISC
(constant (+NCURSES-VERSION-MAJOR+ "NCURSES_VERSION_MAJOR"))
(constant (+NCURSES-VERSION-MINOR+ "NCURSES_VERSION_MINOR"))
(constant (+NCURSES-VERSION-PATCH+ "NCURSES_VERSION_PATCH"))
(constant (+NCURSES-WIDECHAR+ "NCURSES_WIDECHAR"))

;; X/OPEN Attributes
(constant (+WA-ATTRIBUTES+ "WA_ATTRIBUTES"))
(constant (+WA-NORMAL+ "WA_NORMAL"))
(constant (+WA-STANDOUT+ "WA_STANDOUT"))
(constant (+WA-UNDERLINE+ "WA_UNDERLINE"))
(constant (+WA-REVERSE+ "WA_REVERSE"))
(constant (+WA-BLINK+ "WA_BLINK"))
(constant (+WA-DIM+ "WA_DIM"))
(constant (+WA-BOLD+ "WA_BOLD"))
(constant (+WA-ALTCHARSET+ "WA_ALTCHARSET"))
(constant (+WA-INVIS+ "WA_INVIS"))
(constant (+WA-PROTECT+ "WA_PROTECT"))
(constant (+WA-HORIZONTAL+ "WA_HORIZONTAL"))
(constant (+WA-LEFT+ "WA_LEFT"))
(constant (+WA-LOW+ "WA_LOW"))  
(constant (+WA-RIGHT+ "WA_RIGHT"))
(constant (+WA-TOP+ "WA_TOP"))
(constant (+WA-VERTICAL+ "WA_VERTICAL"))
(constant (+WA-ITALIC+ "WA_ITALIC"))

;; colors
(constant (+COLOR-BLACK+ "COLOR_BLACK"))
(constant (+COLOR-RED+ "COLOR_RED"))
(constant (+COLOR-GREEN+ "COLOR_GREEN"))
(constant (+COLOR-YELLOW+ "COLOR_YELLOW"))
(constant (+COLOR-BLUE+ "COLOR_BLUE"))
(constant (+COLOR-MAGENTA+ "COLOR_MAGENTA"))
(constant (+COLOR-CYAN+ "COLOR_CYAN"))
(constant (+COLOR-WHITE+ "COLOR_WHITE"))

;; attributes
(constant (+A-NORMAL+ "A_NORMAL"))
(constant (+A-ATTRIBUTES+ "A_ATTRIBUTES"))
(constant (+A-CHARTEXT+ "A_CHARTEXT"))
(constant (+A-COLOR+ "A_COLOR"))
(constant (+A-STANDOUT+ "A_STANDOUT"))
(constant (+A-UNDERLINE+ "A_UNDERLINE"))
(constant (+A-REVERSE+ "A_REVERSE"))
(constant (+A-BLINK+ "A_BLINK"))
(constant (+A-DIM+ "A_DIM"))
(constant (+A-BOLD+ "A_BOLD"))
(constant (+A-ALTCHARSET+ "A_ALTCHARSET"))
(constant (+A-INVIS+ "A_INVIS"))
(constant (+A-PROTECT+ "A_PROTECT"))
(constant (+A-HORIZONTAL+ "A_HORIZONTAL"))
(constant (+A-LEFT+ "A_LEFT"))
(constant (+A-LOW+ "A_LOW"))
(constant (+A-RIGHT+ "A_RIGHT"))
(constant (+A-TOP+ "A_TOP"))
(constant (+A-VERTICAL+ "A_VERTICAL"))
(constant (+A-ITALIC+ "A_ITALIC"))

;; mouse interface
(constant (+NCURSES-BUTTON-RELEASED+ "NCURSES_BUTTON_RELEASED"))
(constant (+NCURSES-BUTTON-PRESSED+ "NCURSES_BUTTON_PRESSED"))
(constant (+NCURSES-BUTTON-CLICKED+ "NCURSES_BUTTON_CLICKED"))
(constant (+NCURSES-DOUBLE-CLICKED+ "NCURSES_DOUBLE_CLICKED"))
(constant (+NCURSES-TRIPLE-CLICKED+ "NCURSES_TRIPLE_CLICKED"))
(constant (+NCURSES-RESERVED-EVENT+ "NCURSES_RESERVED_EVENT"))

;; event masks
(constant (+BUTTON1-RELEASED+ "BUTTON1_RELEASED"))
(constant (+BUTTON1-PRESSED+ "BUTTON1_PRESSED"))
(constant (+BUTTON1-CLICKED+ "BUTTON1_CLICKED"))
(constant (+BUTTON1-DOUBLE-CLICKED+ "BUTTON1_DOUBLE_CLICKED"))
(constant (+BUTTON1-TRIPLE-CLICKED+ "BUTTON1_TRIPLE_CLICKED"))

(constant (+BUTTON2-RELEASED+ "BUTTON2_RELEASED"))
(constant (+BUTTON2-PRESSED+ "BUTTON2_PRESSED"))
(constant (+BUTTON2-CLICKED+ "BUTTON2_CLICKED"))
(constant (+BUTTON2-DOUBLE-CLICKED+ "BUTTON2_DOUBLE_CLICKED"))
(constant (+BUTTON2-TRIPLE-CLICKED+ "BUTTON2_TRIPLE_CLICKED"))

(constant (+BUTTON3-RELEASED+ "BUTTON3_RELEASED"))
(constant (+BUTTON3-PRESSED+ "BUTTON3_PRESSED"))
(constant (+BUTTON3-CLICKED+ "BUTTON3_CLICKED"))
(constant (+BUTTON3-DOUBLE-CLICKED+ "BUTTON3_DOUBLE_CLICKED"))
(constant (+BUTTON3-TRIPLE-CLICKED+ "BUTTON3_TRIPLE_CLICKED"))

(constant (+BUTTON4-RELEASED+ "BUTTON4_RELEASED"))
(constant (+BUTTON4-PRESSED+ "BUTTON4_PRESSED"))
(constant (+BUTTON4-CLICKED+ "BUTTON4_CLICKED"))
(constant (+BUTTON4-DOUBLE-CLICKED+ "BUTTON4_DOUBLE_CLICKED"))
(constant (+BUTTON4-TRIPLE-CLICKED+ "BUTTON4_TRIPLE_CLICKED"))

(constant (+BUTTON5-RELEASED+ "BUTTON5_RELEASED"))
(constant (+BUTTON5-PRESSED+ "BUTTON5_PRESSED"))
(constant (+BUTTON5-CLICKED+ "BUTTON5_CLICKED"))
(constant (+BUTTON5-DOUBLE-CLICKED+ "BUTTON5_DOUBLE_CLICKED"))
(constant (+BUTTON5-TRIPLE-CLICKED+ "BUTTON5_TRIPLE_CLICKED"))

(constant (+BUTTON-CTRL+ "BUTTON_CTRL"))
(constant (+BUTTON-SHIFT+ "BUTTON_SHIFT"))
(constant (+BUTTON-ALT+ "BUTTON_ALT"))
(constant (+REPORT-MOUSE-POSITION+ "REPORT_MOUSE_POSITION"))

(constant (+ALL-MOUSE-EVENTS+ "ALL_MOUSE_EVENTS"))

(constant (+KEY-CODE-YES+ "KEY_CODE_YES"))
(constant (+KEY-MIN+ "KEY_MIN"))
(constant (+KEY-BREAK+ "KEY_BREAK"))
(constant (+KEY-SRESET+ "KEY_SRESET"))
(constant (+KEY-RESET+ "KEY_RESET"))
(constant (+KEY-DOWN+ "KEY_DOWN"))
(constant (+KEY-UP+ "KEY_UP"))
(constant (+KEY-LEFT+ "KEY_LEFT"))
(constant (+KEY-RIGHT+ "KEY_RIGHT"))
(constant (+KEY-HOME+ "KEY_HOME"))
(constant (+KEY-BACKSPACE+ "KEY_BACKSPACE"))
(constant (+KEY-F0+ "KEY_F0"))
;;;TODO other keys
(constant (+KEY-DL+ "KEY_DL"))
(constant (+KEY-IL+ "KEY_IL"))
(constant (+KEY-DC+ "KEY_DC"))
(constant (+KEY-IC+ "KEY_IC"))
(constant (+KEY-EIC+ "KEY_EIC"))
(constant (+KEY-CLEAR+ "KEY_CLEAR"))
(constant (+KEY-EOS+ "KEY_EOS"))
(constant (+KEY-EOL+ "KEY_EOL"))
(constant (+KEY-SF+ "KEY_SF"))
(constant (+KEY-SR+ "KEY_SR"))
(constant (+KEY-NPAGE+ "KEY_NPAGE"))
(constant (+KEY-PPAGE+ "KEY_PPAGE"))
(constant (+KEY-STAB+ "KEY_STAB"))
(constant (+KEY-CTAB+ "KEY_CTAB"))
(constant (+KEY-CATAB+ "KEY_CATAB"))
(constant (+KEY-ENTER+ "KEY_ENTER"))
(constant (+KEY-PRINT+ "KEY_PRINT"))
(constant (+KEY-LL+ "KEY_LL"))
(constant (+KEY-A1+ "KEY_A1"))
(constant (+KEY-A3+ "KEY_A3"))
(constant (+KEY-B2+ "KEY_B2"))
(constant (+KEY-C1+ "KEY_C1"))
(constant (+KEY-C3+ "KEY_C3"))
(constant (+KEY-BTAB+ "KEY_BTAB"))
(constant (+KEY-BEG+ "KEY_BEG"))
(constant (+KEY-CANCEL+ "KEY_CANCEL"))
(constant (+KEY-CLOSE+ "KEY_CLOSE"))
(constant (+KEY-COMMAND+ "KEY_COMMAND"))
(constant (+KEY-COPY+ "KEY_COPY"))
(constant (+KEY-CREATE+ "KEY_CREATE"))
(constant (+KEY-END+ "KEY_END"))
(constant (+KEY-EXIT+ "KEY_EXIT"))
(constant (+KEY-FIND+ "KEY_FIND"))
(constant (+KEY-HELP+ "KEY_HELP"))
(constant (+KEY-MARK+ "KEY_MARK"))
(constant (+KEY-MESSAGE+ "KEY_MESSAGE"))
(constant (+KEY-MOVE+ "KEY_MOVE"))
(constant (+KEY-NEXT+ "KEY_NEXT"))
(constant (+KEY-OPEN+ "KEY_OPEN"))
(constant (+KEY-OPTIONS+ "KEY_OPTIONS"))
(constant (+KEY-PREVIOUS+ "KEY_PREVIOUS"))
(constant (+KEY-REDO+ "KEY_REDO"))
(constant (+KEY-REFERENCE+ "KEY_REFERENCE"))
(constant (+KEY-REFRESH+ "KEY_REFRESH"))
(constant (+KEY-REPLACE+ "KEY_REPLACE"))
(constant (+KEY-RESTART+ "KEY_RESTART"))
(constant (+KEY-RESUME+ "KEY_RESUME"))
(constant (+KEY-SAVE+ "KEY_SAVE"))
(constant (+KEY-SBEG+ "KEY_SBEG"))
(constant (+KEY-SCANCEL+ "KEY_SCANCEL"))
(constant (+KEY-SCOMMAND+ "KEY_SCOMMAND"))
(constant (+KEY-SCOPY+ "KEY_SCOPY"))
(constant (+KEY-SCREATE+ "KEY_SCREATE"))
(constant (+KEY-SDC+ "KEY_SDC"))
(constant (+KEY-SDL+ "KEY_SDL"))
(constant (+KEY-SELECT+ "KEY_SELECT"))
(constant (+KEY-SEND+ "KEY_SEND"))
(constant (+KEY-SEOL+ "KEY_SEOL"))
(constant (+KEY-SEXIT+ "KEY_SEXIT"))
(constant (+KEY-SFIND+ "KEY_SFIND"))
(constant (+KEY-SHELP+ "KEY_SHELP"))
(constant (+KEY-SHOME+ "KEY_SHOME"))
(constant (+KEY-SIC+ "KEY_SIC"))
(constant (+KEY-SLEFT+ "KEY_SLEFT"))
(constant (+KEY-SMESSAGE+ "KEY_SMESSAGE"))
(constant (+KEY-SMOVE+ "KEY_SMOVE"))
(constant (+KEY-SNEXT+ "KEY_SNEXT"))
(constant (+KEY-SOPTIONS+ "KEY_SOPTIONS"))
(constant (+KEY-SPREVIOUS+ "KEY_SPREVIOUS"))
(constant (+KEY-SPRINT+ "KEY_SPRINT"))
(constant (+KEY-SREDO+ "KEY_SREDO"))
(constant (+KEY-SREPLACE+ "KEY_SREPLACE"))
(constant (+KEY-SRIGHT+ "KEY_SRIGHT"))
(constant (+KEY-SRSUME+ "KEY_SRSUME"))
(constant (+KEY-SSAVE+ "KEY_SSAVE"))
(constant (+KEY-SSUSPEND+ "KEY_SSUSPEND"))
(constant (+KEY-SUNDO+ "KEY_SUNDO"))
(constant (+KEY-SUSPEND+ "KEY_SUSPEND"))
(constant (+KEY-UNDO+ "KEY_UNDO"))
(constant (+KEY-MOUSE+ "KEY_MOUSE"))
(constant (+KEY-RESIZE+ "KEY_RESIZE"))
(constant (+KEY-EVENT+ "KEY_EVENT"))
(constant (+KEY-MAX+ "KEY_MAX"))


