(in-package #:binding)

(include "ncurses.h")

;; MISC
(constant (+NCURSES_VERSION_MAJOR+ "NCURSES_VERSION_MAJOR"))
(constant (+NCURSES_VERSION_MINOR+ "NCURSES_VERSION_MINOR"))
(constant (+NCURSES_VERSION_VERSION_PATCH+ "NCURSES_VERSION_PATCH"))
(constant (+NCURSES_WIDECHAR+ "NCURSES_WIDECHAR"))

;; X/OPEN Attributes
(constant (+WA_ATTRIBUTES+ "WA_ATTRIBUTES"))
(constant (+WA_NORMAL+ "WA_NORMAL"))
(constant (+WA_STANDOUT+ "WA_STANDOUT"))
(constant (+WA_UNDERLINE+ "WA_UNDERLINE"))
(constant (+WA_REVERSE+ "WA_REVERSE"))
(constant (+WA_BLINK+ "WA_BLINK"))
(constant (+WA_DIM+ "WA_DIM"))
(constant (+WA_BOLD+ "WA_BOLD"))
(constant (+WA_ALTCHARSET+ "WA_ALTCHARSET"))
(constant (+WA_INVIS+ "WA_INVIS"))
(constant (+WA_PROTECT+ "WA_PROTECT"))
(constant (+WA_HORIZONTAL+ "WA_HORIZONTAL"))
(constant (+WA_LEFT+ "WA_LEFT"))
(constant (+WA_LOW+ "WA_LOW"))  
(constant (+WA_RIGHT+ "WA_RIGHT"))
(constant (+WA_TOP+ "WA_TOP"))
(constant (+WA_VERTICAL+ "WA_VERTICAL"))
(constant (+WA_ITALIC+ "WA_ITALIC"))

;; colors
(constant (+COLOR_BLACK+ "COLOR_BLACK"))
(constant (+COLOR_RED+ "COLOR_RED"))
(constant (+COLOR_GREEN+ "COLOR_GREEN"))
(constant (+COLOR_YELLOW+ "COLOR_YELLOW"))
(constant (+COLOR_BLUE+ "COLOR_BLUE"))
(constant (+COLOR_MAGENTA+ "COLOR_MAGENTA"))
(constant (+COLOR_CYAN+ "COLOR_CYAN"))
(constant (+COLOR_WHITE+ "COLOR_WHITE"))

;; attributes
(constant (+A_NORMAL+ "A_NORMAL"))
(constant (+A_ATTRIBUTES+ "A_ATTRIBUTES"))
(constant (+A_CHARTEXT+ "A_CHARTEXT"))
(constant (+A_COLOR+ "A_COLOR"))
(constant (+A_STANDOUT+ "A_STANDOUT"))
(constant (+A_UNDERLINE+ "A_UNDERLINE"))
(constant (+A_REVERSE+ "A_REVERSE"))
(constant (+A_BLINK+ "A_BLINK"))
(constant (+A_DIM+ "A_DIM"))
(constant (+A_BOLD+ "A_BOLD"))
(constant (+A_ALTCHARSET+ "A_ALTCHARSET"))
(constant (+A_INVIS+ "A_INVIS"))
(constant (+A_PROTECT+ "A_PROTECT"))
(constant (+A_HORIZONTAL+ "A_HORIZONTAL"))
(constant (+A_LEFT+ "A_LEFT"))
(constant (+A_LOW+ "A_LOW"))
(constant (+A_RIGHT+ "A_RIGHT"))
(constant (+A_TOP+ "A_TOP"))
(constant (+A_VERTICAL+ "A_VERTICAL"))
(constant (+A_ITALIC+ "A_ITALIC"))

;; mouse interface
(constant (+NCURSES_BUTTON_RELEASED+ "NCURSES_BUTTON_RELEASED"))
(constant (+NCURSES_BUTTON_PRESSED+ "NCURSES_BUTTON_PRESSED"))
(constant (+NCURSES_BUTTON_CLICKED+ "NCURSES_BUTTON_CLICKED"))
(constant (+NCURSES_DOUBLE_CLICKED+ "NCURSES_DOUBLE_CLICKED"))
(constant (+NCURSES_TRIPLE_CLICKED+ "NCURSES_TRIPLE_CLICKED"))
(constant (+NCURSES_RESERVED_EVENT+ "NCURSES_RESERVED_EVENT"))

;; event masks
(constant (+BUTTON1_RELEASED+ "BUTTON1_RELEASED"))
(constant (+BUTTON1_PRESSED+ "BUTTON1_PRESSED"))
(constant (+BUTTON1_CLICKED+ "BUTTON1_CLICKED"))
(constant (+BUTTON1_DOUBLE_CLICKED+ "BUTTON1_DOUBLE_CLICKED"))
(constant (+BUTTON1_TRIPLE_CLICKED+ "BUTTON1_TRIPLE_CLICKED"))

(constant (+BUTTON2_RELEASED+ "BUTTON2_RELEASED"))
(constant (+BUTTON2_PRESSED+ "BUTTON2_PRESSED"))
(constant (+BUTTON2_CLICKED+ "BUTTON2_CLICKED"))
(constant (+BUTTON2_DOUBLE_CLICKED+ "BUTTON2_DOUBLE_CLICKED"))
(constant (+BUTTON2_TRIPLE_CLICKED+ "BUTTON2_TRIPLE_CLICKED"))

(constant (+BUTTON3_RELEASED+ "BUTTON3_RELEASED"))
(constant (+BUTTON3_PRESSED+ "BUTTON3_PRESSED"))
(constant (+BUTTON3_CLICKED+ "BUTTON3_CLICKED"))
(constant (+BUTTON3_DOUBLE_CLICKED+ "BUTTON3_DOUBLE_CLICKED"))
(constant (+BUTTON3_TRIPLE_CLICKED+ "BUTTON3_TRIPLE_CLICKED"))

(constant (+BUTTON4_RELEASED+ "BUTTON4_RELEASED"))
(constant (+BUTTON4_PRESSED+ "BUTTON4_PRESSED"))
(constant (+BUTTON4_CLICKED+ "BUTTON4_CLICKED"))
(constant (+BUTTON4_DOUBLE_CLICKED+ "BUTTON4_DOUBLE_CLICKED"))
(constant (+BUTTON4_TRIPLE_CLICKED+ "BUTTON4_TRIPLE_CLICKED"))

(constant (+BUTTON5_RELEASED+ "BUTTON5_RELEASED"))
(constant (+BUTTON5_PRESSED+ "BUTTON5_PRESSED"))
(constant (+BUTTON5_CLICKED+ "BUTTON5_CLICKED"))
(constant (+BUTTON5_DOUBLE_CLICKED+ "BUTTON5_DOUBLE_CLICKED"))
(constant (+BUTTON5_TRIPLE_CLICKED+ "BUTTON5_TRIPLE_CLICKED"))

(constant (+BUTTON_CTRL+ "BUTTON_CTRL"))
(constant (+BUTTON_SHIFT+ "BUTTON_SHIFT"))
(constant (+BUTTON_ALT+ "BUTTON_ALT"))
(constant (+REPORT_MOUSE_POSITION+ "REPORT_MOUSE_POSITION"))

(constant (+ALL_MOUSE_EVENTS+ "ALL_MOUSE_EVENTS"))

(constant (+KEY_CODE_YES+ "KEY_CODE_YES"))
(constant (+KEY_MIN+ "KEY_MIN"))
(constant (+KEY_BREAK+ "KEY_BREAK"))
(constant (+KEY_SRESET+ "KEY_SRESET"))
(constant (+KEY_RESET+ "KEY_RESET"))
(constant (+KEY_DOWN+ "KEY_DOWN"))
(constant (+KEY_UP+ "KEY_UP"))
(constant (+KEY_LEFT+ "KEY_LEFT"))
(constant (+KEY_RIGHT+ "KEY_RIGHT"))
(constant (+KEY_HOME+ "KEY_HOME"))
(constant (+KEY_BACKSPACE+ "KEY_BACKSPACE"))
(constant (+KEY_F0+ "KEY_F0"))
;;;TODO other keys
(constant (+KEY_DL+ "KEY_DL"))
(constant (+KEY_IL+ "KEY_IL"))
(constant (+KEY_DC+ "KEY_DC"))
(constant (+KEY_IC+ "KEY_IC"))
(constant (+KEY_EIC+ "KEY_EIC"))
(constant (+KEY_CLEAR+ "KEY_CLEAR"))
(constant (+KEY_EOS+ "KEY_EOS"))
(constant (+KEY_EOL+ "KEY_EOL"))
(constant (+KEY_SF+ "KEY_SF"))
(constant (+KEY_SR+ "KEY_SR"))
(constant (+KEY_NPAGE+ "KEY_NPAGE"))
(constant (+KEY_PPAGE+ "KEY_PPAGE"))
(constant (+KEY_STAB+ "KEY_STAB"))
(constant (+KEY_CTAB+ "KEY_CTAB"))
(constant (+KEY_CATAB+ "KEY_CATAB"))
(constant (+KEY_ENTER+ "KEY_ENTER"))
(constant (+KEY_PRINT+ "KEY_PRINT"))
(constant (+KEY_LL+ "KEY_LL"))
(constant (+KEY_A1+ "KEY_A1"))
(constant (+KEY_A3+ "KEY_A3"))
(constant (+KEY_B2+ "KEY_B2"))
(constant (+KEY_C1+ "KEY_C1"))
(constant (+KEY_C3+ "KEY_C3"))
(constant (+KEY_BTAB+ "KEY_BTAB"))
(constant (+KEY_BEG+ "KEY_BEG"))
(constant (+KEY_CANCEL+ "KEY_CANCEL"))
(constant (+KEY_CLOSE+ "KEY_CLOSE"))
(constant (+KEY_COMMAND+ "KEY_COMMAND"))
(constant (+KEY_COPY+ "KEY_COPY"))
(constant (+KEY_CREATE+ "KEY_CREATE"))
(constant (+KEY_END+ "KEY_END"))
(constant (+KEY_EXIT+ "KEY_EXIT"))
(constant (+KEY_FIND+ "KEY_FIND"))
(constant (+KEY_HELP+ "KEY_HELP"))
(constant (+KEY_MARK+ "KEY_MARK"))
(constant (+KEY_MESSAGE+ "KEY_MESSAGE"))
(constant (+KEY_MOVE+ "KEY_MOVE"))
(constant (+KEY_NEXT+ "KEY_NEXT"))
(constant (+KEY_OPEN+ "KEY_OPEN"))
(constant (+KEY_OPTIONS+ "KEY_OPTIONS"))
(constant (+KEY_PREVIOUS+ "KEY_PREVIOUS"))
(constant (+KEY_REDO+ "KEY_REDO"))
(constant (+KEY_REFERENCE+ "KEY_REFERENCE"))
(constant (+KEY_REFRESH+ "KEY_REFRESH"))
(constant (+KEY_REPLACE+ "KEY_REPLACE"))
(constant (+KEY_RESTART+ "KEY_RESTART"))
(constant (+KEY_RESUME+ "KEY_RESUME"))
(constant (+KEY_SAVE+ "KEY_SAVE"))
(constant (+KEY_SBEG+ "KEY_SBEG"))
(constant (+KEY_SCANCEL+ "KEY_SCANCEL"))
(constant (+KEY_SCOMMAND+ "KEY_SCOMMAND"))
(constant (+KEY_SCOPY+ "KEY_SCOPY"))
(constant (+KEY_SCREATE+ "KEY_SCREATE"))
(constant (+KEY_SDC+ "KEY_SDC"))
(constant (+KEY_SDL+ "KEY_SDL"))
(constant (+KEY_SELECT+ "KEY_SELECT"))
(constant (+KEY_SEND+ "KEY_SEND"))
(constant (+KEY_SEOL+ "KEY_SEOL"))
(constant (+KEY_SEXIT+ "KEY_SEXIT"))
(constant (+KEY_SFIND+ "KEY_SFIND"))
(constant (+KEY_SHELP+ "KEY_SHELP"))
(constant (+KEY_SHOME+ "KEY_SHOME"))
(constant (+KEY_SIC+ "KEY_SIC"))
(constant (+KEY_SLEFT+ "KEY_SLEFT"))
(constant (+KEY_SMESSAGE+ "KEY_SMESSAGE"))
(constant (+KEY_SMOVE+ "KEY_SMOVE"))
(constant (+KEY_SNEXT+ "KEY_SNEXT"))
(constant (+KEY_SOPTIONS+ "KEY_SOPTIONS"))
(constant (+KEY_SPREVIOUS+ "KEY_SPREVIOUS"))
(constant (+KEY_SPRINT+ "KEY_SPRINT"))
(constant (+KEY_SREDO+ "KEY_SREDO"))
(constant (+KEY_SREPLACE+ "KEY_SREPLACE"))
(constant (+KEY_SRIGHT+ "KEY_SRIGHT"))
(constant (+KEY_SRSUME+ "KEY_SRSUME"))
(constant (+KEY_SSAVE+ "KEY_SSAVE"))
(constant (+KEY_SSUSPEND+ "KEY_SSUSPEND"))
(constant (+KEY_SUNDO+ "KEY_SUNDO"))
(constant (+KEY_SUSPEND+ "KEY_SUSPEND"))
(constant (+KEY_UNDO+ "KEY_UNDO"))
(constant (+KEY_MOUSE+ "KEY_MOUSE"))
(constant (+KEY_RESIZE+ "KEY_RESIZE"))
(constant (+KEY_EVENT+ "KEY_EVENT"))

(constant (+KEY_MAX+ "KEY_MAX"))
