;;;; package.lisp
(defpackage #:raw-ncurses-binding
  (:nicknames #:binding)
  (:use #:cl #:cffi)
  (:export
   ;;INTERFACE
   #:addchstr
   #:addnstr
   #:addstr
   #:attroff
   #:attron
   #:attrset
   #:attr-get
   #:attr-off
   #:attr-on
   #:attr-set
   #:baudrate
   #:beep
   #:bkgd
   #:bkgdset
   #:border
   #:box
   #:can-change-color
   #:cbreak
   #:chgat
   #:clear
   #:clearok
   #:clrtobot
   #:clrtoeol
   #:color-content
   #:color-set
   #:COLOR-PAIR
   #:copywin
   #:curs-set
   #:def-prog-mode
   #:def-shell-mode
   #:delay-output
   #:delch
   #:delscreen
   #:delwin
   #:deleteln
   #:derwin
   #:doupdate
   #:dupwin
   #:echo
   #:echochar
   #:erase
   #:endwin
   #:erasechar
   #:filter
   #:flash
   #:flushinp
   #:getbkgd
   #:getch
   #:getnstr
   #:getstr
   #:getwin
   #:halfdelay
   #:has-colors
   #:has-ic
   #:has-il
   #:hline
   #:idcok
   #:idlok
   #:immedok
   #:inch
   #:inchnstr
   #:inchstr
   #:initscr
   #:init-color
   #:init-pair
   #:innstr
   #:insch
   #:insdelln
   #:insertln
   #:insnstr
   #:insstr
   #:instr
   #:intrflush
   #:isendwin
   #:is-linetouched
   #:is-wintouched
   #:keyname
   #:keypad
   #:killchar
   #:leaveok
   #:longname
   #:meta
   #:move
   #:mvaddch
   #:mvaddchnstr
   #:mvaddchstr
   #:mvaddnstr
   #:mvaddstr
   #:mvchgat
   #:mvcur
   #:mvdelch
   #:mvderwin
   #:mvgetch
   #:mvgetnstr
   #:mvgetstr
   #:mvhline
   #:mvinch
   #:mvinchnstr
   #:mvinchstr
   #:mvinnstr
   #:mvinsch
   #:mvinsnstr
   #:mvinsstr
   #:mvinstr
   #:mvprintw
   #:mvscanw
   #:mvvline
   #:mvwaddch
   #:mvwaddchnstr
   #:mvwaddchstr
   #:mvwaddnstr
   #:mvwaddstr
   #:mvwchgat
   #:mvwdelch
   #:mvwgetch
   #:mvwgetnstr
   #:mvwgetstr
   #:mvwhline
   #:mvwin
   #:mvwinch
   #:mvwinchnstr
   #:mvwinchstr
   #:mvwinnstr
   #:mvwinsch
   #:mvwinsnstr
   #:mvwinsstr
   #:mvwinstr
   #:mvwprintw
   #:mvwscanw
   #:mvwvline
   #:napms
   #:newpad
   #:newterm
   #:newwin
   #:nl
   #:nocbreak
   #:nodelay
   #:noecho
   #:nonl
   #:noqiflush
   #:noraw
   #:notimeout
   #:overlay
   #:overwrite
   #:pair-content
   #:PAIR-NUMBER
   #:pechochar
   #:pnoutrefresh
   #:prefresh
   #:printw
   #:putwin
   #:qiflush
   #:raw
   #:redrawwin
   #:refresh
   #:resetty
   #:reset-prog-mode
   #:reset-shell-mode
   #:ripoffline
   #:savetty
   #:scanw
   #:scr-dump
   #:scr-init
   #:scrl
   #:scroll
   #:scrollok
   #:scr-restore
   #:scr-set
   #:setscrreg
   #:set-term
   #:slk-attroff
   #:slk-attr-off
   #:slk-attron
   #:slk-attr-on
   #:slk-attrset
   #:slk-attr
   #:slk-attr-set
   #:slk-clear
   #:slk-color
   #:slk-init
   #:slk-label
   #:slk-noutrefresh
   #:slk-refresh
   #:slk-restore
   #:slk-set
   #:slk-touch
   #:standout
   #:standend
   #:start-color
   #:subpad
   #:subwin
   #:syncok
   #:termattrs
   #:termname
   #:timeout
   #:touchline
   #:touchwin
   #:typeahead
   #:ungetch
   #:untouchwin
   #:use-env
   #:use-tioctl
   #:vidattr
   #:vidputs
   #:vline
   #:vwprintw
   #:vw-printw
   #:vwscanw
   #:vw-scanw
   #:waddch
   #:waddchnstr
   #:waddchstr
   #:waddnstr
   #:waddstr
   #:wattron
   #:wattroff
   #:wattrset
   #:wattr-get
   #:wattr-on
   #:wattr-off
   #:wattr-set
   #:wbkgd
   #:wbkgdset
   #:wborder
   #:wchgat
   #:wclear
   #:wclrtobot
   #:wclrtoeol
   #:wcolor-set
   #:wcursyncup
   #:wdelch
   #:wdeleteln
   #:wechochar
   #:werase
   #:wgetch
   #:wgetnstr
   #:wgetstr
   #:whline
   #:winch
   #:winchnstr
   #:winchstr
   #:winnstr
   #:winsch
   #:winsdelln
   #:winsertln
   #:winsnstr
   #:winsstr
   #:winstr
   #:wmove
   #:wnoutrefresh
   #:wprintw
   #:wredrawln
   #:wrefresh
   #:wscanw
   #:wscrl
   #:wsetscrreg
   #:wstandout
   #:wstandend
   #:wsyncdown
   #:wsyncup
   #:wtimeout
   #:wtouchln
   #:wvline

   ;; window attributes
   #:wgetparent
   #:is_cleared
   #:is_idcok
   #:is_idlok
   #:is_immedok
   #:is_keypad
   #:is_leaveok
   #:is_nodelay
   #:is_notimeout
   #:is_pad
   #:is_scollok
   #:is_subwin
   #:is_syncok
   #:wgetdelay
   #:wgetscrreg

   ;; mouse support
   #:getmouse
   #:ungetmouse
   #:mousemask
   #:wenclose
   #:mouse_trafo
   #:wmouse_trafo
   #:mouseinterval


   
   ;; CONSTANTS
   #:+NCURSES_VERSION_MAJOR+
   #:+NCURSES_VERSION_MINOR+
   #:+NCURSES_VERSION_VERSION_PATCH+
   #:+NCURSES_WIDECHAR+

   ;; X/OPEN Attributes
   #:+WA_ATTRIBUTES+
   #:+WA_NORMAL+
   #:+WA_STANDOUT+
   #:+WA_UNDERLINE+
   #:+WA_REVERSE+
   #:+WA_BLINK+
   #:+WA_DIM+
   #:+WA_BOLD+
   #:+WA_ALTCHARSET+
   #:+WA_INVIS+
   #:+WA_PROTECT+
   #:+WA_HORIZONTAL+
   #:+WA_LEFT+
   #:+WA_LOW+
   #:+WA_RIGHT+
   #:+WA_TOP+
   #:+WA_VERTICAL+
   #:+WA_ITALIC+

   ;; colors
   #:+COLOR_BLACK+
   #:+COLOR_RED+
   #:+COLOR_GREEN+
   #:+COLOR_YELLOW+
   #:+COLOR_BLUE+
   #:+COLOR_MAGENTA+
   #:+COLOR_CYAN+
   #:+COLOR_WHITE+

   ;; attributes
   #:+A_NORMAL+
   #:+A_ATTRIBUTES+
   #:+A_CHARTEXT+
   #:+A_COLOR+
   #:+A_STANDOUT+
   #:+A_UNDERLINE+
   #:+A_REVERSE+
   #:+A_BLINK+
   #:+A_DIM+
   #:+A_BOLD+
   #:+A_ALTCHARSET+
   #:+A_INVIS+
   #:+A_PROTECT+
   #:+A_HORIZONTAL+
   #:+A_LEFT+
   #:+A_LOW+
   #:+A_RIGHT+
   #:+A_TOP+
   #:+A_VERTICAL+
   #:+A_ITALIC+

   ))
